refactor(ci): refactor workflow

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -7,53 +7,26 @@ defaults:
     shell: bash
 
 jobs:
-  # Check that the project is able to configure the current user
-  # This is the main use case, except for the fact that the current user is root due to GitHub Actions defaults
-  # This might not be representative, so here we just check that configuring the current user works
-  # Also, this job also checks formatting
+  # Check that the project is able to configure the current user.
+  # This is the main use case, except for the fact that the current user is root due to GitHub Actions defaults.
+  # This might not be representative, so here we just check that configuring the current user works.
   check_current_user:
     env:
+      # GitHub Actions set HOME to /github/home, which is not detectable by Ansible's `ansible.builtin.getent` task.
+      # Thus, set it to default `/root`.
       HOME: /root
     runs-on: ubuntu-24.04
     container: ubuntu:24.04
     steps:
-      # checkout action falls back to REST API if it does not find 'git',
-      # which is a case in our virgin container
-      # This leads to a missing .git directory and complaining
-      # format & lint check step
-      # As an exception, let's install git.
-      # More precise checks will be done in another jobs
-      - name: Install git
-        run: apt update && apt-get install --yes --no-install-recommends git ca-certificates
       - name: Checkout repository
         uses: actions/checkout@v4
-        with:
-          # Checkout must be onto the original commit, not a single PR
-          # Otherwise lint will not see full history and diagnose secrets leakage
-          fetch-depth: 0
-          ref: ${{ github.event.pull_request.head.sha }}
-      # Checkout action sets repo as safe, but this does not look like to work inside container
-      - name: Mark repo as safe
-        run: git config --system --add safe.directory $(pwd)
       - name: Config
         run: ./main.sh config
       - name: Check idempotence
         run: ./main.sh config --verify-unchanged
-      # All format & lint checks only available after complete machine setup
-      # So, we need to do them in one of the check jobs
-      - name: Check format
-        run: |
-          ./main.sh format
-          if [[ -n "$(git diff)" ]]; then
-            echo "Code is not formatted."
-            git diff
-            exit 1
-          fi
-      - name: Check lint
-        run: ./main.sh lint
 
-  # As mentioned, previous check for the root user might not be representative
-  # Thus, all the main checks are done by root for the "random_user"
+  # As mentioned, previous check for the root user might not be representative.
+  # Thus, all the main checks are done by root for the "random_user".
   check:
     runs-on: ubuntu-24.04
     container: ${{ matrix.image }}
@@ -75,7 +48,7 @@ jobs:
           - fedora:41
           - fedora:42
 
-  # Check that the project is able to configure remote host, with a user different from the current one
+  # Check that the project is able to configure remote host, with a user different from the current one.
   check_remote:
     runs-on: ubuntu-24.04
     steps:
@@ -86,8 +59,39 @@ jobs:
       - name: Check remote idempotence
         run: ./main.sh config --host dotfiles_ubuntu_22.04 --user random_user --mode minimal --verify-unchanged
 
+  lint:
+    runs-on: ubuntu-24.04
+    container: ubuntu:24.04
+    steps:
+      # checkout action falls back to REST API if it does not find 'git', which is a case in our virgin container.
+      # This leads to a missing .git directory and failed secrets leakage check.
+      # As an exception, let's install git.
+      - name: Install git
+        run: apt update && apt-get install --yes --no-install-recommends git ca-certificates
+      # Checkout must be onto the original commit, not a single PR.
+      # Otherwise lint will not see full history and diagnose secrets leakage.
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.sha }}
+      # Checkout action sets repo as safe, but this does not look like to work inside container.
+      - name: Mark repo as safe
+        run: git config --system --add safe.directory $(pwd)
+      - name: Check format
+        run: |
+          ./main.sh format
+          if [[ -n "$(git diff)" ]]; then
+            echo "Code is not formatted."
+            git diff
+            exit 1
+          fi
+      - name: Lint
+        run: ./main.sh lint
+
   scripts:
     runs-on: ubuntu-24.04
+    container: ubuntu:24.04
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -95,8 +99,6 @@ jobs:
         run: ./main.sh graph
       - name: Check update works
         run: ./main.sh update
-      - name: Show diff
-        run: git diff
 
 name: dotfiles workflow
 
